## https://vale.sh/docs
## https://vale.sh/docs/vale-ini
## https://vale.sh/docs/vale-ini#global-configuration
## https://github.com/chrischinchilla/vale-vscode

MinAlertLevel = error
Packages = write-good
StylesPath = ".vale/styles"

[formats]
markdoc = md
markdown = md

[*.md]
BasedOnStyles = write-good

[README.md]
BasedOnStyles = Vale
